jk_static_pages_homepage:
    path:     /home/{part}
    defaults: { _controller: JKStaticPagesBundle:Default:index, part: bio }

jk_static_pages_formationpage:
    path:     /formation/{part}
    defaults: { _controller: JKStaticPagesBundle:Default:formation, part: humansciences }

jk_static_pages_experiencepage:
    path:     /experience/{part}
    defaults: { _controller: JKStaticPagesBundle:Default:experience, part: school }

jk_static_pages_contactpage:
    path:     /contact/{part}
    defaults: { _controller: JKStaticPagesBundle:Default:contact, part: regular }